### ISSUE TITLE
change doc  

### ISSUE THREAD

**Issue by ghost** [naps62/capistrano3-monit#3]
I guess  the ReadMe line  stating: 

```
gem 'capistrano3-monit', github: 'naps62/capistrano3-monit'
```

should be changed to : 

```
gem 'capistrano-monit'
```

Otherwise the Capful line 

   require 'capistrano/monit'

will raise an error during bundle install : 

```
$ cap staging setup
(Backtrace restricted to imported tasks)
cap aborted!
LoadError: cannot load such file -- capistrano/monit
```

**Comment by naps62** [comment]
@erwin16 You're right about the error, but that's not the right solution.

You should probably be able to do:

``` ruby
gem 'capistrano3-monit', require: 'caspitrano/monit'
```

But even better would be to do this:

``` ruby
# Gemfile
# this is not needed in the app itself, so no point in requiring it
gem 'capistrano3-monit', require: false

# Capfile
require 'capistrano/monit
```

Notice that `capistrano-monit` is actually a different gem that already existed on Rubygems when I created mine (their repo here: https://github.com/ebertech/capistrano-monit)

That one only supports Capistrano 2. Or at least it did at the time. That was the reason I wrote my own. And since the name was already being used, I needed to add the `3` in the name

I'll add this info to Readme to clarify.
